import Head from "next/head";
import { Search } from "../components/Search";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Repuestos Climatización</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido <h1 className="font-extrabold text-transparent bg-clip-text bg-gradient-to-bl from-pink-500 to-yellow-500">Nombre</h1>
        </h1>
        <h3 className={styles.description}>
          ¿Que deseas buscar?
        </h3>
          <Search />
      </main>
    </>
  );
}
